### ISSUE TITLE
useful category: data storage format

### ISSUE THREAD

**Issue by emtiu** [restic/others#69]
While researching backup solutions, I found that there are fundamental differences in the way the backups themselves are stored.

A prime concern for me is compatibility and being able to read/restore backups with minimal tooling. From this perspective, backup solutions seem to fall into two broad categories:

- restic, borg, bup: _the backup is a git repo, it cannot be read without the software that created it_
- rsnapshot, backintime: _the backup is just a folder structure with copies of the files inside, readable like any other folder structure_ (however: no deduplication, native encryption etc.)

Do you think there's a good way to incorporate these into your list? Approproate tags might be `plaintext` and `git`, and possibly others.

**Comment by cfcs** [comment]
I think `git` is misleading in this case since the storage formats, while *git-like* (in that they keep binary blobs separate from the directory layouts), are not readable using `git`.

Many of these tools offer `fuse`-wrappers that allow you to inspect the snapshots just like if they were plain files, so that might be useful for people who need to e.g. search for or filter items without extracting the whole thing. We could have a tag for that? (something like `fs-browseable` ?)

I'm a little bit wary of adding tags that split the list into exactly two categories; we could end up with a ton of "mandatory" tags. I think a `filesystem` tag (like your `plaintext`) might be a good idea to tag the ones that plop your files in a layout that resembles the original filesystem layout. Would that work for you?

**Comment by emtiu** [comment]
Yes, that would be helpful: `filesystem`, as in _"the files are stored **in plaintext and maintaining the original folder layout** in a target filesystem without blob abstractions or fuse-layering"_.

If I'm not mistaken, this should imply that advanced functions like encryption, network storage or deduplication can still be applied separately by using an appropriate target filesystem (layer) like LUKS, NFS, ZFS etc.

This tag could be applied to **backintime** and **rsnapshot** for a start.

**Comment by cfcs** [comment]
I agree @emtiu, would you have time to prepare a pull request with the required changes to the tag descriptions and with the `filesystem` tag applied to the ones you know to be applicable for it?

**Comment by emtiu** [comment]
Closing in favor of #71.
